config/routes.rb
TouristShopApp::Application.routes.draw do

  resources :reviews

  get "sessions/new", as: :new_session
  post "sessions/create", as: :sessions

 
    
  # get "brands/:id" => "brands#show", as: :brand
  
  get "logout" => 'sessions#destroy', as: :logout   
  
   resources :products
   
   get "brands/show"
   get "brands/:id" => "brands#show", :as => :brand
   

   root to: "products#index"   
 
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :logo, :name
  
  has_many :products
  has_many :reviews, :through => :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :brand_id, :name, :price
  
  belongs_to :brand
  
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :body, :product_id, :rating, :title, :user_id
  
  belongs_to :user
  belongs_to :product
  
  validates :rating, :numericality => {:only_integer => true,
                                        :greater_than_or_equal_to => 1,
                                        :less_than_or_equal_to => 5 }
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :login, :password
  
  has_many 
  # has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  
  before_filter :show_session_data
  # before_filter :find_logged_in_user
  #         
  #         def find_logged_in_user
  #            @user = User.find_by_id(session[:login_id])
  #          end
  #          
  def show_session_data
      logger.debug "---------------------------"
      logger.debug "Session: #{session.inspect}"
      logger.debug "-" * 50
    end
  
  
  
end

app/controllers/brand_controller.rb
class BrandsController < ApplicationController
  
  

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  
  def show
    @brand = Brand.find(params[:id])
    @products = @brand.products.order("LOWER(name) asc")                                     
    
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  def index
    @products = Product.order('LOWER(name) asc').all
  
    end
    
  def show
    @product = Product.find(params[:id])
  end
  def new
    @product = Product.new
  end
  def create
    @product = Product.new(params[:product])
    
    if @product.save
      redirect_to root_url, notice: "New Product Added!"
    else
      render :new
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])
    @review.user = @user

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def destroy
     session[:login_id] = nil
     flash[:notice] = "GoodBye amigo!"
     redirect_to root_url
   
   end
  
  
  def new
  end

  def create
    user = User.find_by_login(params[:login])
    
    if user
      if user.authenticate(params[:password])
          sessions[:login_id] = user.id
          redirect_to root_url, notice: "Hola, #{user.login}"
      else
          redirect_to root_url, notice: "wrong password man!"
      end
    else
        redirect_to root_url, notice: "wrong login ID Hermano!"
    end
  end  
end

 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/brands/show.html.erb
<h1> <%= @brand.name %></h1>


<head> 
	<li> Product Name</li>
	<li> Price </li>
	

<body>
	<% @products.each do |value| %>  
	 	
	<ul>
		<li><%= value.name  %></li>
		<li><%= number_to_currency(value.price) %></li>
	</ul>
		<% end %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TouristShopApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div id="header">
	  <h1><%= link_to "Tourist Shop", root_url %></h1>

	  <% if @user %>
	    <p>Hello, <%= @user.login %>
	    <%= link_to "Logout", logout_url %>
	    | <%= link_to "Add a New Product", new_product_url  %></p>
	  <% else %>
	    <%= link_to "Login", new_session_url %>
	  <% end %>
	</div>

	<% if flash[:notice] %>
	  <p style="color: white; background: red; padding: 4px">
	  <%= flash[:notice] %>
	  </p>
	<% end %>



<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1> Product Category </h1>

<p> Buy Something from us! </p>

<table>
	
	
	
	<thead>
    <tr>
      <th>Brand</th>
      <th>Product Name</th>
      <th>Avg Rating</th>
      <th>Price</th>
    </tr>
  </thead>
	
	
	<tbody>
	<% @products.each do |product| %>
		<tr>
			<td><%= link_to product.brand.name, brand_url(product.brand.id) %></td>
			<ltd><%= link_to product.name, product_url(product) %></td>
			<td><%= product.reviews.average('rating').to_i%></td>
			<td><%= number_to_currency(product.price)%></td>
			
		
			

		</tr>
		
	<% end %>
	</tbody>
</table>

app/views/products/new.html.erb
<h1>Add a New Product</h1>

<%= form_for @products do |f| %>
  
  <p>
    <%= f.label :brand_id %>
    <%= f.collection_select :brand_id, Brand.all, :id, :name %>	

  </p>
  
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </p>
  
  <%= f.submit %>
  
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<p>This product is gonna cost ya <%= number_to_currency(@product.price) %></p>

<%= link_to "Review This Product", new_review_url %>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.collection_select :product_id, Product.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.select :rating, 1..5 %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :rows => 4 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>User</th>
    <th>Product</th>
    <th>Rating</th>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.user_id %></td>
    <td><%= review.product_id %></td>
    <td><%= review.rating %></td>
    <td><%= review.title %></td>
    <td><%= review.body %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>


<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @review.user_id %>
</p>

<p>
  <b>Product:</b>
  <%= @review.product_id %>
</p>

<p>
  <b>Rating:</b>
  <%= @review.rating %>
</p>

<p>
  <b>Title:</b>
  <%= @review.title %>
</p>

<p>
  <b>Body:</b>
  <%= @review.body %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>